# Generated by Django 5.2.2 on 2025-06-27 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_product_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={},
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='created_at',
        ),
    ]
