# Generated by Django 5.2.2 on 2025-07-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='status',
            field=models.CharField(choices=[('thumbnail', 'Thumbnail'), ('product_image', 'Product Image')], default='product_image', max_length=20),
        ),
    ]
