# Generated by Django 5.2.2 on 2025-07-08 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_productimage_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='status',
            new_name='type',
        ),
    ]
