# Generated by Django 5.2.2 on 2025-10-09 12:17
from django.db import migrations, connection


def set_order_pk_sequence(apps, schema_editor):
    """Set the primary key sequence for Order table to start from 10000."""
    with connection.cursor() as cursor:
        # 'your_app_name_order' is the table name; adjust if you use a custom db_table
        cursor.execute("""
            SELECT setval(
                pg_get_serial_sequence('core_order', 'id'),
                9999,
                false
            );
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_appnotification_user'),
    ]

    operations = [
        migrations.RunPython(set_order_pk_sequence),
    ]
