# Generated by Django 5.2.2 on 2025-12-29 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_set_order_pk_sequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('large', 'Large'), ('medium', 'Medium'), ('small', 'Small')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('offer_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productvariants', to='core.product')),
            ],
            options={
                'verbose_name_plural': 'ProductVariants',
                'unique_together': {('product', 'category')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.productvariant'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.productvariant'),
        ),

        # Data migration: create a default ProductVariant per Product and copy price/stock/description
        migrations.RunPython(
            code=lambda apps, schema_editor: (
                (lambda Product, ProductVariant, CartItem, OrderItem: [
                    (
                        lambda p: (
                            (lambda v: (CartItem.objects.filter(product=p).update(variant=v), OrderItem.objects.filter(product=p).update(variant=v)))
                            (ProductVariant.objects.create(
                                product=p,
                                category='medium',
                                description=getattr(p, 'description', None),
                                stock=getattr(p, 'stock', 0) or 0,
                                original_price=getattr(p, 'price', None)
                            ))
                        )
                    )(p)
                for p in Product.objects.all()])
            )(
                apps.get_model('core', 'Product'),
                apps.get_model('core', 'ProductVariant'),
                apps.get_model('core', 'CartItem'),
                apps.get_model('core', 'OrderItem')
            ),
            reverse_code=migrations.RunPython.noop,
        ),

        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product', 'variant')},
        ),

        # # Now safe to remove product-level fields (price/compare_at_price/stock)
        # migrations.RemoveField(
        #     model_name='product',
        #     name='compare_at_price',
        # ),
        # migrations.RemoveField(
        #     model_name='product',
        #     name='price',
        # ),
        # migrations.RemoveField(
        #     model_name='product',
        #     name='stock',
        # ),
    ]
