# Generated by Django 5.2.2 on 2026-01-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_product_compare_at_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='category',
            field=models.CharField(choices=[('large', 'Large'), ('medium', 'Medium'), ('small', 'Small'), ('pot', 'Pot'), ('clump', 'Clump'), ('rhizome', 'Rhizome'), ('plant', 'Plant')], max_length=20),
        ),
    ]
