# Generated by Django 5.2.2 on 2026-01-03 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_productvariant_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='category',
            new_name='variant_type',
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'variant_type')},
        ),
    ]
