# Generated by Django 5.2.2 on 2026-01-09 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_rename_category_productvariant_variant_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['id'], 'verbose_name_plural': 'ProductVariants'},
        ),
    ]
