# Generated by Django 5.2.2 on 2026-02-08 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_order_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockNotification',
        ),
    ]
