# Generated by Django 5.2.2 on 2025-06-25 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_category_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
