# Generated by Django 5.2.2 on 2025-06-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_tag_remove_product_tags_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
